# Good reference: https://github.com/cBioPortal/cbioportal-frontend/blob/master/.circleci/config.yml

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0-browsers
    steps:
      - checkout
      - run:
          command:
            npm test
